/* ***************************************************************************
Question comes from Lalaina Randrianarisoa

MODIFICATION LOG: 
VER			DATE		AUTHOR			DESCRIPTION
1.0			3/14/24		CHRIS WEISS		ANSWER TO Lalaina's question
Marginal Complexity

Lalaina Randrianarisoa

Q1 - Business User question - Marginal complexity: Who are the top three customers 
by purchase amount in the Customer table?
 ***************************************************************************** */

USE AdventureWorks2022;

SELECT TOP (3) so.CustomerID,
       FORMAT(SUM(so.TotalDue),'C','en-us') AS 'TotalPurchased',
	   p.PersonType,
	   p.FirstName,
	   p.LastName
     
  FROM [AdventureWorks2022].[Sales].[SalesOrderHeader] AS so
  INNER JOIN Sales.Customer AS cus ON so.CustomerID=cus.CustomerID
  INNER JOIN Person.Person as p ON cus.PersonID=p.BusinessEntityID
  GROUP BY so.CustomerID,p.PersonType,p.FirstName,p.LastName
  ORDER BY SUM(so.TotalDue) DESC;

 

/* ***************************************************************************
Question comes from JeAnna Kremer

MODIFICATION LOG: 
VER			DATE		AUTHOR			DESCRIPTION
1.0			3/14/24		CHRIS WEISS		ANSWER TO JeAnna's question 
Marginal Complexity:

JeAnna Kremer
Business User Questions:
Q1: What is the average wage for our Employees?
*************************************************************************** */

USE AdventureWorks2022;

SELECT PayFrequency, FORMAT(AVG(Rate),'C','en-us') AS 'AvgPayRate',
FORMAT(MIN(Rate),'C','en-us') AS 'MinPay',FORMAT(MAX(Rate),'C','en-us') AS 'MaxPay'
  FROM [AdventureWorks2022].[HumanResources].[EmployeePayHistory]
  GROUP BY PayFrequency
  ORDER BY PayFrequency;


/* ***************************************************************************
MODIFICATION LOG: 
VER			DATE		AUTHOR			DESCRIPTION
1.0			3/14/24		CHRIS WEISS		ANSWER TO IAN NDHLOVU'S QUESTION
Moderate complexity:

Ian Mandlaenkosi Ndhlovu
Q2 - Business User question -  
      1. I am interested in the percentage of the revenue generated by each store. 
	  What percentage of revenue is generated by each store 
	  and which store yields the highest revenue per unit sold? 

	  This is the answer to the above question.  I had to use 3 inner joins and figure
	  out the GROUP BY command.  This was super challenging for me. Not knowing what the unit
	  were.  I wasn't sure how to calculate revenue per unit sold.  I asked 
	  on the board, but I hadn't received an answer as of programming time.
*************************************************************************** */

USE AdventureWorks2022;

SELECT soh.CustomerID, st.name, 
sum(sod.OrderQTY) AS 'QtySold', FORMAT(SUM(sod.Linetotal),'C','en-us') AS 'TotalRevenue in 2014'
FROM Sales.SalesOrderHeader AS soh
INNER JOIN (SELECT SalesOrderID, SUM(LINETOTAL) AS 'Linetotal', 
SUM(ORDERQTY) AS 'OrderQTY' FROM SALES.SalesOrderDetail GROUP BY SalesOrderID) 
AS sod ON sod.SalesOrderID=soh.SalesOrderID
INNER JOIN Sales.Customer AS cus ON soh.CustomerID=cus.CustomerID
INNER JOIN  Sales.Store AS st ON cus.StoreID=st.BusinessEntityID
WHERE DATEPART(year,soh.OrderDate) = 2014 
GROUP BY soh.CustomerID, st.name 
ORDER BY st.Name
;



/* ***************************************************************************
MODIFICATION LOG: 
VER			DATE		AUTHOR			DESCRIPTION
1.0			3/14/24		CHRIS WEISS		ANSWER TO IAN NDHLOVU'S QUESTION
Moderate complexity:

Ian Mandlaenkosi Ndhlovu
Q2 - Business User question -  
      1. I am interested in the percentage of the revenue generated by each store. 
	  What percentage of revenue is generated by each store 
	  and which store yields the highest revenue per unit sold? 

	 I thought that this was per territory.  I include this here because it was what 
	 I thought the answer was. The real answer to the real question was above.
***************************************************************************   */


USE AdventureWorks2022;
SELECT TerritoryID AS 'Territory',[Name], [Group], CountryRegionCode, 
FORMAT(SalesYTD,'C','en-us') AS 'YearToDateSales',
FORMAT((SELECT SUM(SalesYTD) FROM SALES.SalesTerritory),'C','en-us') AS 'TotalSales', 
FORMAT(SalesYTD * 100 / (SELECT SUM(SalesYTD) FROM Sales.SalesTerritory),'N','en-us') AS 'PercentagePerStore'
-- (SalesYTD/'TotalSales') AS 'Percentage'
FROM Sales.SalesTerritory

ORDER BY SalesYTD; 


/* *************************************************************************** 
MODIFICATION LOG: 
VER			DATE		AUTHOR			DESCRIPTION
1.0			3/14/24		CHRIS WEISS		ANSWER TO AkumiahDesmond's Question 
Moderate complexity

Question
Please give a list of our vendors, the credit rating, 
whose minimum quantity is more than 20 and last receipt cost is between 30 – 45.


 ***************************************************************************   */

USE AdventureWorks2022;

SELECT prdven.BusinessEntityID, purven.AccountNumber, purven.name, purven.creditrating,
AVG(MinOrderQty) AS 'Avg-MinOrderQty', AVG(LastReceiptCost) AS 'Avg-LastReceiptCost'
FROM Purchasing.ProductVendor AS prdven
INNER JOIN Purchasing.Vendor AS purven ON prdven.BusinessEntityID=purven.BusinessEntityID
GROUP BY prdven.BusinessEntityID,purven.AccountNumber,purven.name,purven.CreditRating
HAVING AVG(MinOrderQty) > 20 AND AVG(LastReceiptCost) BETWEEN 30 AND 45
ORDER BY CreditRating;



/*  ***************************************************************************
Question comes from Me, Chris Weiss
More Complex

MODIFICATION LOG: 
VER			DATE		AUTHOR			DESCRIPTION
1.0			3/14/24		CHRIS WEISS		ANSWER TO My More complex question

What inventory is currently in production?  Give the productID, Product Name, 
Product Number, Qty on order, What the production unit price per item is, 
the standard cost of each item, the list price of each item, and 
the amount of profit made in dollars and percentage by 
calculating the difference between unit production cost and list price.

 ***************************************************************************  */

USE AdventureWorks2022;

SELECT distinct po.ProductID, p.ProductNumber, p.name, po.OrderQty, 
po.UnitPrice, p.ListPrice, 
IIF((p.listprice<po.unitprice),((p.listprice/po.unitprice)*-100),((p.listprice/po.unitprice)*100)) AS 'ProfitMargin %', 
FORMAT((po.orderqty *(p.ListPrice-po.UnitPrice)),'C', 'en-us') AS 'PotentialMoneyMade'
FROM production.product AS p
LEFT JOIN Purchasing.PurchaseOrderDetail AS po
ON p.ProductID=po.ProductID
WHERE po.ProductID IS NOT NULL 
ORDER BY ListPrice DESC;



/*  ***************************************************************************
Question comes from Me, Chris Weiss
More Complex 

MODIFICATION LOG: 
VER			DATE		AUTHOR			DESCRIPTION
1.0			3/14/24		CHRIS WEISS		ANSWER TO My More complex question 

What is the current value of all inventory we hold? I need productID, Product Name, Product Number, 
Standard Cost, List Price, quantity on hand per LocationID. Sorted by Product Name.

 ***************************************************************************   */

USE ADVENTUREWORKS2022;

SELECT i.LocationID, p.ProductID, p.Name, p.ProductNumber, p.StandardCost, p.ListPrice, 
	i.Quantity,  (i.quantity * p.standardcost) AS 'Inv_Cost- (qty*stdcost)',
	(i.quantity * p.listprice) AS 'Inv_Value - (qty*lstprc)' 
FROM production.Product AS p
INNER JOIN production.ProductInventory AS i ON p.ProductID=i.ProductID
WHERE p.listprice > 0
ORDER BY i.LocationID,p.name; 


/* ***************************************************************************
Question comes from Austin Baker
Metadata Question
MODIFICATION LOG: 
VER			DATE		AUTHOR			DESCRIPTION
1.0			3/14/24		CHRIS WEISS		ANSWER TO Austin's Question 

Q7 - Metadata question: Can you make a list of tables
in AdventureWorks that contain SalesOrderID or ProductID?
***************************************************************************  */



SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLUMN_DEFAULT
FROM AdventureWorks2022.INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME LIKE 'SalesOrderID' OR COLUMN_NAME LIKE 'ProductID'
ORDER BY COLUMN_NAME;


/* ***************************************************************************
Question comes from Musharib Mazher
Metadata Question
MODIFICATION LOG: 
VER			DATE		AUTHOR			DESCRIPTION
1.0			3/14/24		CHRIS WEISS		ANSWER TO Musharib's Question 

Q7 - Metadata question: Can you provide a list of tables in 
AdventureWorks that contain columns
related to employee information such as EmployeeID, JobTitle, and DepartmentID?
***************************************************************************  */



SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLUMN_DEFAULT
FROM AdventureWorks2022.INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME LIKE 'EmployeeID' OR COLUMN_NAME LIKE 'JobTitle' OR COLUMN_NAME LIKE 'DepartmentID'
ORDER BY COLUMN_NAME;
